### ISSUE TITLE
[QUESTION] Is this project dead?

### ISSUE THREAD

**Issue by MarcusCemes** [axe312ger/sqip#100]
I love this package! I've been using it for a while, but ran into an issue on Windows. In my opinion, this placeholder technique looks much better than any other alternative.

The issue has been fixed and merged in https://github.com/axe312ger/sqip/commit/206f683a85e6fb2c4d1adae012f585feb0e0de41, however, the commit hasn't been published to npm... Which means without building and symlinking the package manually, this is unusable on Windows. Could we get another alpha version bump? Or should I look to package my own sqip binaries?

**Comment by MarcusCemes** [comment]
Just realised that the README is recommending installing the alpha branch, which is why I didn't encounter this before. I will go back to the old stable release, but would love to see this active again!

**Comment by axe312ger** [comment]
Not dead for sure, I'll continue working on SQIP as soon I find time.

I am pretty sure the alpha with teh windows fix was released in version alpha 28?

**Comment by MarcusCemes** [comment]
That's great to hear! SQIP with triangles and no-blur is just beautiful.

I didn't realise that the primitive plugin was in fact up to date with the repository, therefore meaning that the latest npm release is not built correctly.

If you check [line 94](https://unpkg.com/browse/sqip-plugin-primitive@1.0.0-alpha.28/dist/sqip-plugin-primitive.js) on unpkg, commit https://github.com/axe312ger/sqip/commit/206f683a85e6fb2c4d1adae012f585feb0e0de41 just isn't there, despite the commit being tagged as `1.0.0-alpha.27` and the plugin version being `1.0.0-alpha.28`. I'm unfamiliar with this repository's deployment process.

**Comment by axe312ger** [comment]
I published a new version, including the fix for #93. This should resolve your issues :)

Will now continue testing and fixing everything for #90
