### ISSUE TITLE
Vulnerability in js-yaml dependency

### ISSUE THREAD

**Issue by WagnerMoreira** [axe312ger/sqip#115]
The `js-yaml` which is a dependency of multiple packages listed in [package.json](https://github.com/axe312ger/sqip/blob/master/package.json) is reported to be a vulnerability.

Please check https://www.npmjs.com/advisories/813.

## Steps to reproduce
- Create a blank project.
```
- npm install --save sqip
- npm audit
```

## Expected results
- npm audit reports no vulnerabilities.

## Actual results
npm audit reports a high severity vulnerability:

<img width="693" alt="Screen Shot 2020-07-28 at 6 14 02 PM" src="https://user-images.githubusercontent.com/611845/88722738-2177ee80-d0fe-11ea-892b-1c767230f9bd.png">

### Note:
The advisory mentions:
> Versions of js-yaml prior to 3.13.1 are vulnerable to Code Injection.

I found something using`~3.7.0` in the yarn.lock file, please check https://github.com/axe312ger/sqip/blob/master/yarn.lock#L8054

**Comment by sido420** [comment]
Any updates on this? Its a security vulnerability

**Comment by axe312ger** [comment]
The dependency is updated in the upcoming v1 release. Try it via `@next`. The readme in this repo is up2date.
