### ISSUE TITLE
How to use sqip with PNG's with transparent backgrounds?

### ISSUE THREAD

**Issue by pdobrescu** [axe312ger/sqip#117]
Hello folks and thanks for this great project!

While it works excellent in most of the cases, there is the situation of PNG's with transparent backgrounds, which are turned into ugly looking LQIP's that have a large dark/black area around them.

After digging several hours into this, with no real results, I decided to open this issue. 

Here's an example so you can better understand the issue:

Original image (taken from https://github.com/fogleman/primitive/issues/54 and also avilable [here](https://another.dobrestii.ro/wp-content/uploads/2021/01/beers.png)):

![beers](https://user-images.githubusercontent.com/1044106/104088828-65902300-5248-11eb-9ebf-52a355b5b25f.png)

I have `sqip` installed on a Debian machine and after running

`sqip -n 100 -m 0 -bg #ffffff00 source.png -o target.svg` I get this result (I can't upload SVG's unfortunately, so I took a snapshot):

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1044106/104088961-7db47200-5249-11eb-82d4-9b1aed051a70.png">

https://dev.shortpixel.ai/spai/q_lqip/https://another.dobrestii.ro/wp-content/uploads/2021/01/beers.png?7

I found the `#ffffff00` format in here https://github.com/fogleman/primitive/issues/54, but even if the result seems to have a white background when it is rendered, it is still annoyingly black on the exterior. And it's really far away from the original image!

The desired output would be a lighter color (I do not especially expect transparency, even if that would be really nice), but the black that you see, looks really bad. 

Do you have any ideas on how to make this happen? Should I use other parameters? Any suggestions would be highly appreciated! Thank you!

**Comment by axe312ger** [comment]
If you try the upcoming v1 of sqip, the plugin for primitive supports the background color setting.

1. You can set this color to the background color you will display the image on top of it.

2. If you want to get "real transparency" within the SVG, you could write a small plugin that removes the rectangle which is used for the SVGs background.

The result should be close to what fogleman posted in his answer: https://github.com/fogleman/primitive/issues/54#issuecomment-348063688

Hope this helps,

Benedikt

**Comment by pdobrescu** [comment]
Hello again and thanks for your tips @axe312ger !

I upgraded to the latest canary build (currently `1.0.0-alpha.36`) and after trying tens of possibilities, I didn't manage to set a starting white background using the `-bg` parameter. As a conclusion, maybe there's something that I'm not doing right. 

I am running this command, using the CLI:

`sqip -i beers.png -o beers.svg -p primitive blur --primitive-bg '#FFFFFF00' -m 0 -b 20 -n 50`

I tried also directly with `-bg`, with or without `'`, with or without the trailing `00`, with and without mentioning the plugins, I get more or less the same effect. I was also trying to force an error in order to check what is the actual command that generates the svg and I managed to obtain this (as a part of the error message, when I set `n` to zero):

`/usr/local/lib/node_modules/sqip-plugin-primitive/vendor/primitive-linux-x64 -i - -o - -n 0 -m 0 -s 942 -rep 0 -a 128 -bg #513f47 -j 0`

My conclusion is that for some reason, the `-bg` parameter isn't actually passed to the `primitive` plugin, as its starting background is different as you can see from the command (and indeed `#513f47` is the color of the initial rectangle from the resulting SVG).

Apart from that, I also tried manually removing the starting rectangle, but I didn't get transparency within the output SVG. And down below is the SVG output, if it helps in any way, as I can't upload it here.

I'm more than open to any suggestions you might have, as I'm pretty much blocked and not sure which way to go from here. 

Many thanks again!

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="695" height="942" viewBox="0 0 696 942"><filter id="b"><feGaussianBlur stdDeviation="20"/></filter> <rect width="100%" height="100%" fill="#513f47"/> <g filter="url(#b)"><g transform="scale(3.679688) translate(0.5 0.5)"> <g transform="translate(69.015421 68.270938) rotate(0.426341) scale(58.429377 21.821165)"><ellipse fill="#ffff97" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <g transform="translate(121.481987 188.801304) rotate(-38.605628) scale(43.426607 30.937083)"><ellipse fill="#f8e0dc" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <ellipse fill="#000000" fill-opacity="0.501961" cx="166" cy="65" rx="46" ry="97"/> <g transform="translate(114.901624 240.534321) rotate(3.507073) scale(176.379360 31.689506)"><ellipse fill="#000000" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <polygon fill="#ffff9b" fill-opacity="0.501961" points="129,21 59,7 52,39"/> <g transform="translate(13.448377 14.139361) rotate(221.458998) scale(39.123452 58.565838)"><ellipse fill="#000000" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <g transform="translate(69.953269 120.966517) rotate(552.282908) scale(157.479390 31.228233)"><ellipse fill="#0b0000" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <ellipse fill="#000000" fill-opacity="0.501961" cx="188" cy="145" rx="31" ry="255"/> <g transform="translate(84.179851 188.523498) rotate(-70.210149) scale(29.007785 67.825759)"><ellipse fill="#ba9d9c" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <g transform="translate(4.792368 150.190563) rotate(265.060623) scale(149.165255 15.913640)"><ellipse fill="#000000" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <g transform="translate(111.231459 57.788302) rotate(277.694018) scale(46.597113 11.614205)"><ellipse fill="#ffe171" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <polygon fill="#ffe5b5" fill-opacity="0.501961" points="153.265725,226.055276,142.147535,162.064672,142.897126,106.753221,158.870809,146.714570"/> <g transform="translate(57.533740 234.741951) rotate(290.302018) scale(25.948513 116.613561)"><ellipse fill="#000000" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <ellipse fill="#000000" fill-opacity="0.501961" cx="69" cy="2" rx="188" ry="11"/> <ellipse fill="#fff593" fill-opacity="0.501961" cx="59" cy="74" rx="52" ry="10"/> <rect fill="#ffffff" fill-opacity="0.501961" x="108" y="164" width="18" height="58"/> <g transform="translate(134.348477 221.333969) rotate(95.761585) scale(59.147621 9.024915)"><ellipse fill="#1a0200" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <g transform="translate(91 39) rotate(274) scale(18 30)"><rect fill="#000000" fill-opacity="0.501961" x="-0.5" y="-0.5" width="1" height="1"/></g> <polygon fill="#e2ad60" fill-opacity="0.501961" points="125.880201,69.257842,164.935569,62.576998,48.007155,36.825537,91.142070,96.930842"/> <ellipse fill="#000000" fill-opacity="0.501961" cx="174" cy="184" rx="17" ry="255"/> <polygon fill="#f7e2e2" fill-opacity="0.501961" points="22,196 22,139 38,142"/> <ellipse fill="#070000" fill-opacity="0.501961" cx="81" cy="208" rx="5" ry="117"/> <g transform="translate(25.928334 25.444575) rotate(307.481910) scale(21.589501 31.931300)"><ellipse fill="#000000" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <ellipse fill="#ffffff" fill-opacity="0.501961" cx="55" cy="176" rx="4" ry="29"/> <rect fill="#ffffff" fill-opacity="0.501961" x="147" y="150" width="10" height="59"/> <g transform="translate(154.611340 6.041422) rotate(165.075293) scale(35.819845 54.329583)"><ellipse fill="#000000" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <ellipse fill="#ffff9e" fill-opacity="0.501961" cx="82" cy="19" rx="30" ry="7"/> <polygon fill="#000000" fill-opacity="0.501961" points="21,80 -16,133 22,271"/> <rect fill="#000000" fill-opacity="0.501961" x="45" y="150" width="7" height="106"/> <polygon fill="#180500" fill-opacity="0.501961" points="168.567507,103.746318,161.697434,144.983461,125.812138,162.557905,126.893535,177.194163"/> <g transform="translate(139 243) rotate(336) scale(166 52)"><rect fill="#000000" fill-opacity="0.501961" x="-0.5" y="-0.5" width="1" height="1"/></g> <rect fill="#ffffff" fill-opacity="0.501961" x="87" y="159" width="3" height="61"/> <rect fill="#61202f" fill-opacity="0.501961" x="92" y="171" width="16" height="37"/> <polygon fill="#271600" fill-opacity="0.501961" points="57.689636,151.541550,163.313324,150.198334,111.901792,96.358240,-3.932562,79.656747"/> <ellipse fill="#ffff9f" fill-opacity="0.501961" cx="61" cy="30" rx="8" ry="19"/> <polygon fill="#fffdff" fill-opacity="0.501961" points="153.315847,162.999754,126.625668,155.965266,154.937483,149.443547,156.456020,163.390648"/> <rect fill="#fff09d" fill-opacity="0.501961" x="10" y="58" width="34" height="22"/> <rect fill="#ffe488" fill-opacity="0.501961" x="105" y="22" width="19" height="42"/> <polygon fill="#000000" fill-opacity="0.501961" points="101.023157,48.759721,71.279359,46.448072,69.625382,28.722007,110.548399,36.468070"/> <rect fill="#b78465" fill-opacity="0.501961" x="25" y="112" width="8" height="84"/> <polygon fill="#000000" fill-opacity="0.501961" points="114,-16 6,7 179,16"/> <g transform="translate(93.779120 135.321270) rotate(195.454638) scale(3.504792 10.332812)"><ellipse fill="#efc7a5" fill-opacity="0.501961" cx="0" cy="0" rx="1" ry="1"/></g> <polygon fill="#ccb39f" fill-opacity="0.501961" points="67,114 51,130 59,137"/> <polygon fill="#432902" fill-opacity="0.501961" points="177,60 119,71 109,168"/> <polygon fill="#fffeff" fill-opacity="0.501961" points="124,221 127,194 91,223"/> <polygon fill="#5f320a" fill-opacity="0.501961" points="88.772461,68.697788,103.854321,52.797795,73.057348,60.535747,23.169295,54.573536"/> <polygon fill="#7e585d" fill-opacity="0.501961" points="163.984524,177.779646,112.385084,189.518960,127.121865,208.646038,129.784871,158.139593"/> <polygon fill="#e4e6eb" fill-opacity="0.501961" points="25.238175,179.513523,42.641035,200.540420,21.958802,194.295638,22.818696,137.776182"/> <rect fill="#ffffff" fill-opacity="0.501961" x="135" y="204" width="17" height="7"/> <ellipse fill="#000000" fill-opacity="0.501961" cx="18" cy="19" rx="36" ry="34"/> </g></g></svg>```

**Comment by pdobrescu** [comment]
hello again @axe312ger, do you have any updates with regards to this issue, please? any advice would be more than welcome! thank you

**Comment by axe312ger** [comment]
Hey @pdobrescu, 

I expect to have time for SQIP this summer again. Then will get the v1 released (we have a typescript version cooking), and then will look at the open issues.


Have a great start into the summer,
Benedikt

**Comment by pdobrescu** [comment]
hello @axe312ger , I just noticed this commit 41f86332e42b737e7b9865d735fbd09a201b5303 and I was wondering if there are chances that it fixes this issue?

**Comment by axe312ger** [comment]
Yes, maybe. At least it should now set the background color you defined in the options. The TS PR is also getting close to a merge :) 

Also, I can tell you that I now experience the same issue with a customer website that uses transparent pngs. They expect transparent/white background but get black backgrounds. Looks super ugly.

I'll check out how we can fix this as soon I get time, but can't put this on high prio 😅

**Comment by axe312ger** [comment]
Hey @pdobrescu,

thank you for the offer. If someone in your team is good in TS & jest, I really could help in figuring out why these tests time out on CI. They work fine on machine (ofc) -> https://github.com/axe312ger/sqip/pull/120

If we get this PR merged, we can tackle issues in the SVG generation. I'll add this ticket to the v1 milestone.

**Comment by axe312ger** [comment]
I found it! primitive expects the hex color to be passed without hashtag.

Fix including tests will be pushed asap :)

**Comment by axe312ger** [comment]
I committed my changes and tests via 9769d4597fdfca877d1caef1c3f2cd68347fd223

Additionally I remove the background rectangle/path generated by primitive. That way we have real transparent pixels in each svg.

![transparent-background](https://user-images.githubusercontent.com/1737026/167292298-fe5a25b9-474e-42b3-b2a8-66bcc4658673.png)


Turns into
![transparent-background](https://user-images.githubusercontent.com/1737026/167292300-23489714-ae67-4b84-8180-2423d5b6b962.svg)

**Comment by pdobrescu** [comment]
dear @axe312ger, I forgot to thank you for the fixes, alpha.38 has finally solved our issues with the dark background for LQIPs generated from transparent PNGs 😉  much appreciated 🙏 

As for your request, unfortunately, we have no expertise in TS & jest in our team 😶

**Comment by axe312ger** [comment]
Great to hear! Enjoy the new version. Should also be in beta soonish
