### ISSUE TITLE
Error in parsing SVG: Unbound namespace prefix: "xlink"

### ISSUE THREAD

**Issue by httpways** [axe312ger/sqip#118]
Hello,

I try to convert PNG pictures to SVG using the following command:

`node_modules/.bin/sqip -p primitive svgo -n 10 -m 2 --primitive-cores 3 -i $my_png_file -o $my_output_folder`

But I got the following error:

`Error in parsing SVG: Unbound namespace prefix: "xlink"`

Please help,

Thanks

**Comment by axe312ger** [comment]
Where do you get that error? When rendering the SVG or does SQIP itself throw this error?

Any more details about the error message?

Can you share the SQIP version u used and the PNG you tried?

Do you have the issue with other images as well?

**Comment by axe312ger** [comment]
@httpways do you still remember? If no, please just close this :)

**Comment by xerc** [comment]
@axe312ger old/depr. syntax (ref. https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)

**Comment by axe312ger** [comment]
The newer parser should be able to handle this. Can anyone confirm?
