### ISSUE TITLE
Cannot update `node-vibrant`

### ISSUE THREAD

**Issue by aaharu** [axe312ger/sqip#119]
`sqip@1.0.0-alpha.32` depends on `node-vibrant`.
The latest version of `node-vibrant` is `3.2.1-alpha.1`.

https://www.npmjs.com/package/node-vibrant

So, I can't update `node-vibrant` from `3.2.0-alpha` because `3.2.1-alpha.1` doesn't satisfy `^3.2.0-alpha`.

https://github.com/axe312ger/sqip/blob/master/packages/sqip/package.json#L46
```json
"node-vibrant": "^3.2.0-alpha",
```

```
> semver.satisfies('3.2.1-alpha.1', '^3.2.0-alpha')
false
```

**Comment by axe312ger** [comment]
Do you know what changed? Why do you need to update this?


This tool tells me the version range is satisfied:

https://jubianchi.github.io/semver-check/#/^3.2.0-alpha/3.2.1-alpha.1

**Comment by aaharu** [comment]
sorry, it's my misunderstanding.
