### ISSUE TITLE
 dyld: lazy symbol binding failed: Symbol not found: _g_once_impl - Update Sharp Dependency 

### ISSUE THREAD

**Issue by tommyboylab** [axe312ger/sqip#121]
First time reporter, but long time user. I really like your package and it's Primitive SVG generator. I've used it in my project to process all images I've uploaded to generate placeholders that are loaded while images are loading.

Currently I'm facing an issue with sharp within your package being outdated.

```
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
 Referenced from: /Users/thomas/Documents/Github/bff/node_modules/plugin-upload/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/thomas/Documents/Github/bff/node_modules/sqip/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.42.dylib
```

Doing some background research it's referenced there's a conflict packages using outdated Sharps. I'm currently using the solution provided in the link below, but also see you've been working on updating the package to TS in a recent branch.

If it's also possible for you to update the dependencies used in your package, It'd be greatly appreciated. I'd like to continue using it without conflict.

https://github.com/22mahmoud/eleventy-image-example/issues/1

Thanks for creating this awesome package. 👍🏼

**Comment by axe312ger** [comment]
Yeah, absolute sounds like our sharp is to old and your OS is to new.

I will probably run into the same on my new M1.

I have to maintain this repo on low priority, but will have a look into this. We currently prepare a ts rewrite, push out a first beta and then can start adding more features/fixing bugs and getting ready for a v1 stable.


Will keep u posted, just can't promise any timespan.

Cheers

**Comment by axe312ger** [comment]
@tommyboylab sharp is updated for a while and I create SVGs using SQIP on my M1 :)

**Comment by axe312ger** [comment]
(Note: you have to use @next version)

**Comment by kuwts** [comment]
> (Note: you have to use @next version)

How can one do this? Running into this same problem myself.
