### ISSUE TITLE
webp / heif support

### ISSUE THREAD

**Issue by wereHamster** [axe312ger/sqip#122]
Can't use webp or heif images as input images, because it's not supported by node vibrant -> jimp dependency.

I'm not actually interested in the dominant colors though, only in the svg output. It would be nice if the whole code which extracts the dominant colors wouldn't run at all unless I activate it (as a plugin for example). The plugins I currently use are sqip-plugin-primitive, sqip-plugin-blur, sqip-plugin-svgo.

**Comment by axe312ger** [comment]
Hi,

great request. I suggest we do the following:

* by default: try to transform the image to a forma that vibrant understands, probably using sharp.
* add option to disable the color palette generation


I have to maintain this repo on low priority, but will have a look into this. We currently prepare a ts rewrite, push out a first beta and then can start adding more features/fixing bugs and getting ready for a v1 stable.


Will keep u posted, just can't promise any timespan.

Cheers

**Comment by wereHamster** [comment]
AFAICS sharp is already a dependency, so wrapping the buffer in `sharp().png()` wouldn't add too much additional cost, correct? If so, I can try the PR.

Alternative would be to run `.png()` only when we detect an incompatible image format (jimp currently supports png/jpeg/bmp/tiff/gif).

**Comment by wereHamster** [comment]
… see #207

**Comment by axe312ger** [comment]
Uhh nice thanks!

**Comment by axe312ger** [comment]
This is done and released in the v1@canary
