### ISSUE TITLE
Output Image Not cropped to original dimensions

### ISSUE THREAD

**Issue by tettoffensive** [axe312ger/sqip#16]
I have an input jpg image. It seems that the output svg encapsulates the extent of the primitives generated by `primitive` rather than cropping to the dimensions of the input image. Right now I have to do that manually in illustrator.

**Comment by Munter** [comment]
@tettoffensive Do you have a sample image that recreates this problem? I'd like to take a stab at it. Might even be a fix that should go directly to `primitive`

**Comment by arpadcseh** [comment]
Hi @Munter ,
I have the same issue with latest sqip. Here is the test input and output.
![input](https://user-images.githubusercontent.com/1511049/36265333-4ed3cea8-126f-11e8-9be4-ef0e0df254de.jpg)
[output.txt](https://github.com/technopagan/sqip/files/1728319/output.txt)

Note: I had to rename the svg file to txt as github doesn't support it as attachment. 

Hope it helps!
Cheers!

**Comment by canyoudev** [comment]
Probably related? https://github.com/technopagan/sqip/issues/40

**Comment by axe312ger** [comment]
Probably related, too: https://github.com/gatsbyjs/gatsby/issues/5224

**Comment by axe312ger** [comment]
Closing this as I didn't see this issue for a good while in the upcoming v1 which will be out soon.


Try it via '@next'. See the repo readme for installation and usage instructions.
