### ISSUE TITLE
Support configuration options for underlying SVG converter

### ISSUE THREAD

**Issue by funklos** [axe312ger/sqip#22]
Is there any plan to support further configuration of the underlying SVG converter?
In the current version primitive is used to create the SVGs and according to the documentation there are more command line flags available than just the number of shapes, which is configurable by this library.
Our current use case would be the usage of the -bg argument, which can be used to provide a specific background color. We experienced issues with png files with transparent backgrounds, which turn out to be black instead of transparent when converted.
Additionally also the -m argument would be of interest for further experimentation.
I can offer to provide you with a pull request when there is nothing like that currently in the works.. 👍

**Comment by axe312ger** [comment]
+1, would be great if you add more options to the tool.

The setting for `mode` already got released :)

**Comment by axe312ger** [comment]
will be fixed with the new plugin system :)

**Comment by axe312ger** [comment]
Most of these options: https://github.com/fogleman/primitive#command-line-usage

Should end up in: https://github.com/axe312ger/sqip/blob/master/packages/sqip-plugin-primitive/src/sqip-plugin-primitive.js 

The `nth` parameter generates a new image for every frame, we might support this by throwing every result into the image array sqip uses
