### ISSUE TITLE
Probleming running the sqip-command on Mac M1

### ISSUE THREAD

**Issue by sndrem** [axe312ger/sqip#253]
Operating system:
macOS Monterey v. 12.5.1

Node version
```
node -v
v17.9.0
```

Npm version
```
npm -v
8.15.0
```

When running the command
`sqip -i bilde.jpeg -o bilde.svg -m 1 -n 10 -b 9`

I get the error below
```
TypeError: (0 , _sqip.default) is not a function
    at sqipCLI (/Users/sindre/.nvm/versions/node/v17.9.0/lib/node_modules/sqip-cli/dist/sqip-cli.js:194:29)
    at async /Users/sindre/.nvm/versions/node/v17.9.0/lib/node_modules/sqip-cli/dist/wrapper.js:9:3
```

Any idea how to get past the problem so I can run the sqip command?

**Comment by axe312ger** [comment]
Also, you might have installed the wrong versions.

Did you use the command from the readme to install SQIP? 

> npm install sqip@canary sqip-plugin-primitive@canary sqip-plugin-svgo@canary sqip-plugin-data-uri@canary

**Comment by sndrem** [comment]
Node 16 + `npm install sqip@canary sqip-plugin-primitive@canary sqip-plugin-svgo@canary sqip-plugin-data-uri@canary` and `npm install -g sqip-cli@canary` did the trick for me. Thank you!

**Comment by nhoizey** [comment]
I have the same issue on a MacBook Air M2 with SQIP Canary and Node 16:

```shell
TypeError: (0 , _sqip.default) is not a function
    at sqipCLI (/Users/nicolashoizey/.nvm/versions/node/v16.19.0/lib/node_modules/sqip-cli/dist/sqip-cli.js:194:29)
    at async /Users/nicolashoizey/.nvm/versions/node/v16.19.0/lib/node_modules/sqip-cli/dist/wrapper.js:9:3
```

I ran
- `npm install -g sqip@canary sqip-plugin-primitive@canary sqip-plugin-svgo@canary sqip-plugin-data-uri@canary`
- and then `npx sqip -i ./src/photos/**/*.jpg`

@axe312ger should I open a new issue?

**Comment by axe312ger** [comment]
@nhoizey if still exists, please new ticket yeah. It works on my M1 though :/
