### ISSUE TITLE
allow passing buffer as input in node api

### ISSUE THREAD

**Issue by jordangarside** [axe312ger/sqip#38]
Would it be possible to allow passing a buffer as an input (instead of filename) in the Node API?

**Comment by efegurkan** [comment]
I think it would be doable if we could pass it to the primitive directly. Worst case it would need a js implementation of the primitive.

**Comment by Dabolus** [comment]
Seems like primitive does not support a buffer as an input. Having a js implementation of primitive would be great, but I think it will require a lot of time. As a temporary solution, what about saving the buffer as a file in the system's temp directory ([`os.tmpdir()`](https://nodejs.org/api/os.html#os_os_tmpdir)), calling primitive with that file and then deleting it?

**Comment by jordangarside** [comment]
I wound up using [node-primitive](https://github.com/vincentdesmares/node-primitive) which is a js implementation of primitive. It's a little slow, but it works ok.

Saving a temporary file was the route I was going to go if node-primitive didn't work. If you guys don't want to integrate that logic into sqip, then feel free to close this.

**Comment by axe312ger** [comment]
Using node-primitive is not an option yet, since primitive is already pretty slow in it's go implementation.


On the other hand primitive now seems to support passing in from stdin, so passing in a buffer should become possible now :)

**Comment by axe312ger** [comment]
Still somebody looking for this feature? Should be not that hard to implement, but I'll remove it from the initial v1 version.

**Comment by gabrielperales** [comment]
Hi @axe312ger, I need this feature so I'm going to fork the lib. If I manage to make it work I can show you my changes and see if worth to make a PR.

**Comment by axe312ger** [comment]
@gabrielperales yay nice, looking forward

**Comment by gabrielperales** [comment]
Hi @axe312ger I opened #110 , can you check that out and tell me your thoughts?

**Comment by axe312ger** [comment]
I will have a look soon! :)
