### ISSUE TITLE
Async I/O

### ISSUE THREAD

**Issue by Munter** [axe312ger/sqip#5]
It would be helpful if the blocking calls were removed and the API became async

**Comment by axe312ger** [comment]
Ohh yeah, that would be great. Maybe for the next version. What do you think @efegurkan?

**Comment by efegurkan** [comment]
Would be great to add that :+1: @axe312ger

**Comment by bdrtsk** [comment]
Any progress on this, guys? SQIP completly blocks my server even using queue.

**Comment by axe312ger** [comment]
Closing this as the current alpha now fully async
