### ISSUE TITLE
Pixelated effect

### ISSUE THREAD

**Issue by bdrtsky** [axe312ger/sqip#52]
Hello. I just thought it would be cool to have pixelated effect. How do you think it's possible?

**Comment by axe312ger** [comment]
Hmm, its not possible with primitive except u use the triangle mode, but thats not real pixelated.

We are currently working on making [SQIP plugin](#43) based, so if you find a tool that can create that effect in svg's, we can add it do SQIP.

Maybe there is a svg filter that could do similar?

**Comment by technopagan** [comment]
Heyho @bdrtsky! You could use a preparatory step to convert your high-resolution original into a pixelated variant, e.g. via imagemagick‘s „convert“ + scale and then send that already-pixelated variant as input to SQIP. Primitive mode 2 is „rectangle“ and will be aligned to the pixelated input image if possible, depending on how many shapes you allow. So you *can* achieve your desired effect - it just needs a prep-step plus a custom mode when running SQIP.

**Comment by axe312ger** [comment]
Awesome idea @technopagan :)

**Comment by bdrtsky** [comment]
@technopagan sounds interesting! I will try that, thanks for idea.

**Comment by axe312ger** [comment]
After #35 is done, I'd love to create a plugin that creates real pixelated svgs without using primitive. 

Let me know how @technopagan's idea worked out for you @bdrtsky

**Comment by axe312ger** [comment]
@bdrtsky check out https://github.com/axe312ger/sqip/tree/feat/pixels-plugin#examples

Is this what you've been looking for? :)

**Comment by bdrtsky** [comment]
@axe312ger oh yes, this is absolutely awesome :fire: 

Thank you!!!

**Comment by axe312ger** [comment]
`sqip -p pixels -i yourfile.svg` should do it.

A PR to allow setting the number of horizontal pixels would be amazing 😁

**Comment by axe312ger** [comment]
I am down for any alternative approaches that result in a faster browser rendering time.

A few words why this is currently done with just a bunch of rectangles:

With the current implementation of the pixels plugin I had the idea to write another plugin, which replaces each shape with a given one. That way you could have a matrix of your company logo representing the original image. No idea if that would be really useful but I liked the idea 😅

**Comment by axe312ger** [comment]
It is now configurable as well and released in the lastest alpha. Closing here for now.
