### ISSUE TITLE
How to use SQIP effectively for multiple files ?

### ISSUE THREAD

**Issue by willdante** [axe312ger/sqip#53]
Hi,

I'm looking for the most effective way to use SQIP for all images in a directory.

I've managed to make it work running a Windows CMD:
`for %x in (*) do sqip -o ./svg/%x.svg %x`

But when running it in a .bat file, it doesn't work:
`for %%x in (*) do sqip -o ./svg/%%x.svg %%x`

Ideally, I'd like to use the Node API in my Vue/Nuxt website but I don't understand how to do that.
I'm new to dev and would need some help to make the best use of SQIP.

Thanks in advance.

**Comment by willdante** [comment]
Sorry, I was looking to close the issue but it doesn't seem possible.

If it can help, I've found out why my batch wasn't working.

My .bat file was in the img folder where the images to sqip were too.
And it was named sqip.bat, so the sqip command inside my batch was launching the .bat file again and again!

Now it works but I'm still interested in having some tips to use the Node API.

I'm working on a Image Vue component and I'd like it to generate the SQIP version of the related image.
Is it possible ?

**Comment by axe312ger** [comment]
You have to call SQIP for every image separated, then calls are sync at the moment so just loop over your files and push the paths into the SQIP call. Just like it is done here: https://github.com/axe312ger/sqip#node-api

Does this help?

**Comment by willdante** [comment]
Ok, thank you.
