### ISSUE TITLE
Preserve white background

### ISSUE THREAD

**Issue by Jesus82** [axe312ger/sqip#54]
Hi, I have a series of product images (mainly beer bottles and cans) that consist in the product and a white background. When processed through sqip, the background always end up in some light gray color, making the loading effect less smooth. 

Is there any way to preserve the white background in the svg? (either by preprocessing with imagemagick/graphicsmagick or with any other css trick) Thanks in advance!

**Comment by axe312ger** [comment]
Might be fixed with #39
