### ISSUE TITLE
Reduce byte size further by improving SVG data URI encoding

### ISSUE THREAD

**Issue by technopagan** [axe312ger/sqip#58]
Back when we first built SQIP, we went with Base64 encoding for the SVG string so that it was safe to be included inline in HTML because that is when SQIPs make their positive impact. See [the "encodeBase64" function](https://github.com/axe312ger/sqip/blob/129ba71f6a54d0b71a046480a56d7f5129656ccb/packages/sqip-plugin-data-uri/src/sqip-plugin-data-uri.js) in the code.

However, back then, it was already clear to me that SVG, being XML, didn't strictly speaking need full base64 encoding and that we'd be making GZIP's / brotli's dictionaries slightly less successful in compression with the base64 overhead. Yet, no one had built a "proper" SVG data URI encoder at that time, so we went with base64 as a safe, if slightly bloated, bet.

Good news! Times have changed! There's now [https://github.com/tigt/mini-svg-data-uri](https://github.com/tigt/mini-svg-data-uri) available, which is exactly the functionality we need and not a single byte more! Yay! 🎉 It will only encode the characters inside an SVG that are unsafe to be used in a data URI and leave the rest untouched. 

With this library replacing the current base64 encoding, I'd expect that we can reduce the byte size of SQIPs by 3%-10%.

This improvement is very desirable in itself already to make SQIPs as small & fast as possible, but since SQIP byte size is already on par with raster-based LQIPs, we could even consider "reinvesting" these byte size savings into increasing the default shapes count of an uncustomized SQIP run by 1-2 shapes to further improve the visual accuracy of SQIPs.

**Comment by axe312ger** [comment]
Hey Tobias,

thanks for the hint. Already have it on my plate and using it for https://www.npmjs.com/package/gatsby-transformer-sqip

Further I plan to implement it in the https://github.com/axe312ger/sqip/tree/master/packages/sqip-plugin-data-uri plugin :) 

Best,
Benedikt

**Comment by axe312ger** [comment]
🚀 🎉 SQIP `v1.0.0-alpha.25` now beats the old version in initial file size & compression rate:

https://axe312ger.github.io/sqip/
