### ISSUE TITLE
Create a JS port of Primitive to remove the Golang dependency

### ISSUE THREAD

**Issue by technopagan** [axe312ger/sqip#6]
Currently, SQIP relies on Primitive (https://github.com/fogleman/primitive), which is written in Go, being installed. We could remove this unelegant dependency by porting Primitive to JS, maybe by basing our porting work on https://github.com/ondras/primitive.js.

**Comment by robinpokorny** [comment]
@ondras, how difficult you think this would be?

**Comment by ondras** [comment]
Well, PrimitiveJS stands and falls with the 2D `<canvas>` DOM API. If the port is to be server-side, some corresponding lib/api has to be used.

As far as client side is concerned, PrimitiveJS is already a pretty close port of Primitive, using most of the algorithms from the initial Go implementation.

**Comment by axe312ger** [comment]
I made https://github.com/technopagan/sqip/pull/25 to work around this for now.

But ++ on a node version :)

**Comment by axe312ger** [comment]
This is out of scope of this project 🙃
