### ISSUE TITLE
Hot Patch Current NPM release

### ISSUE THREAD

**Issue by MattCatz** [axe312ger/sqip#62]
Hi! I understand that you are hard at work with the next major revision of the of the project but, I was wondering if you could update Legacy branch to fix the js-yaml code injection warning. It would require bumping the dependency of svgo to 1.2.2 

[SVGO patch](https://github.com/svg/svgo/commit/db45845e1cb2b3f8b5228e0e222098d3d638ee2c)

**Comment by axe312ger** [comment]
Hi Matt,

as far as I know svgo v1+ is async, so we have to wait for the next version of sqip to upgrade to the latest svgo. Sorry :(

**Comment by MattCatz** [comment]
Thanks for looking into it.
