### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Adam-Collier** [axe312ger/sqip#68]
Hey currently getting this error when trying to npm install everything 

![image](https://user-images.githubusercontent.com/20065745/59492984-0eff0f00-8e82-11e9-8dcb-4e36fcfdc9c3.png)

Is there a fix for this?

**Comment by axe312ger** [comment]
Hey Adam,

I was missing permissions to release sqip itself on npm, that broke the publishing.

I'll fix this the next days by releasing `v1.0.0-alpha.x`

For now check the legacy readme: https://github.com/axe312ger/sqip/tree/legacy#readme

Best,
Benedikt

**Comment by Adam-Collier** [comment]
Ahh great! thanks for the info 👍 Great work on the library btw!
