### ISSUE TITLE
Tune Primitive to create closer similarity with fewer shapes

### ISSUE THREAD

**Issue by technopagan** [axe312ger/sqip#8]
Currently, Primitive is basically an art project: it uses a random seed as part of its SVG shape generation and is not conscious about the number of shapes it uses to achieve a good similarity. 

Once we've ported Primitive (https://github.com/technopagan/sqip/issues/6), we should consider changing its inner workings to be more efficient in achieving a better similiarity to the input image with fewer shapes. Additionally, we shoud consider removing the random seed so that Primitive's output becomes more deterministic for each input image.

**Comment by eustas** [comment]
There is a way to stuff more details - avoid SVG overhead: https://github.com/eustas/2im
Here is the comparison of SQIP SVG vs no-SVG approach: https://eustas.github.io/2im/twim-vs-sqip.html

**Comment by axe312ger** [comment]
@eustas a plugin to implement 2im into sqip would be amazing. A PR is very welcome :)

This part of the docs should help to create one: https://github.com/axe312ger/sqip/blob/master/CONTRIBUTING.md#create-a-new-plugin

**Comment by axe312ger** [comment]
Closing this as we can now fine tune primitive and have several plugins to play around in the upcoming v1. 

I am very open to a 2im plugin for SQIP. Feel free to open an issue / PR if you want that!
