### ISSUE TITLE
CLI always outputs 300px-width svg

### ISSUE THREAD

**Issue by ria4** [axe312ger/sqip#92]
Hi,

I might be missing something obvious but when I'm running something like this...
`npx sqip -i photo.jpg -n 40 -b 2 -m 1 -w 0 -o photo.svg`
...the output is always 300px wide, instead of keeping the original image width.

Using a standard int (e.g. `-w 1000`) does not change this.

Updating the default CLI 300px width does not change this either.
https://github.com/axe312ger/sqip/blob/891c36649e0b53e052506deb3707ad9ac9e2bc96/packages/sqip-cli/src/sqip-cli.js#L41-L48

The only width that matters seems to be the one below. When changed (either to 0 or >0 value), the output width changes accordingly.
https://github.com/axe312ger/sqip/blob/1b810403ca64ae825564a045ab2690f47579cae1/packages/sqip/src/sqip.js#L121-L133

**Comment by axe312ger** [comment]
Thank you for the bug report and testing the alpha, I'll have a look :)

**Comment by axe312ger** [comment]
Should be fixed with latest alpha. Install from canary branch and let me know :)

**Comment by ria4** [comment]
It works fine now. Thank you for the commit!

**Comment by axe312ger** [comment]
great to hear <3
