### ISSUE TITLE
Win64 error in sqip-plugin-primitive (requiring golang)

### ISSUE THREAD

**Issue by renanvaz** [axe312ger/sqip#94]
Hello, when i run the Skip with the following code:

```js
sqip({
    input: 'in/',
    output: 'out/',
})
.then(result => console.log(result))
.catch(error => console.error(error));
```

The catch receives this message:

`Please ensure that Primitive (https://github.com/fogleman/primitive, writ ten in Golang) is installed and globally available`

Looking the code, the error is caused bacause the file extension `.exe` is not present in the file path at `primitivePath` variable

**Comment by renanvaz** [comment]
To resolve this, just change the line 87 of file "packages/sqip-plugin-primitive/src/sqip-plugin-primitive.js" like this:
```js
const primitivePath = path.join(
  VENDOR_DIR,
  `primitive-${os.platform()}-${os.arch()}${os.platform() == 'win32' && '.exe'}`
)
```

Can you make this change? I cant build to open a pull request here.

**Comment by axe312ger** [comment]
Good catch, thanks. I'll fix this soonish, wanted to do a upgrade round in this repo the next days anyways :)

**Comment by axe312ger** [comment]
Should be fixed with latest alpha. Install from canary branch and let me know :)
